version: '3'

services:
  front:
    build: ./front
    ports:
      - "4200:4200"
    networks:
      default:
        aliases:
          - front
    tty: true
  back:
    build: ./back
    ports:
      - "3001:3001"
    networks:
      default:
        aliases:
          - back
    tty: true
  ubuntu:
    image: ubuntu:latest
    networks:
      default:
        aliases:
          - ubuntu
    tty: true
