version: '3'

services:
  front:
    build: ./front
    ports:
      - "4200:4200"
    volumes:
      - "./front/reservation-app:/reservation-app-front"
  back:
    build: ./back
    ports:
      - "3001:3001"
    volumes:
      - "./back/reservation-app:/reservation-app-back"
